org: keatskeet
app: blueprint-screener-api
service: aws-node-express-api-project
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  httpApi:
    cors:
      allowedOrigins: '*'
      allowedHeaders: '*'
      allowedMethods: '*'

functions:
  api:
    handler: app.sls
    events:
      - httpApi: '*'
