org: keatskeet
app: blueprint-screener-api
service: aws-node-express-api-project
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'
  httpApi:
    cors:
      allowedOrigins: '*'
      allowedHeaders: '*'
      allowedMethods: '*'

functions:
  api:
    handler: dist/app.sls
    events:
      - httpApi: '*'
